# Generated by Django 4.1.7 on 2023-02-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('lanzamiento', models.DateField()),
                ('gano_premio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pintura', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('estilo', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('en_venta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('lanzamiento', models.DateField()),
                ('en_emision', models.BooleanField()),
                ('gano_oscar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videojuego', models.CharField(max_length=50)),
                ('consola', models.CharField(max_length=50)),
                ('es_digital', models.BooleanField()),
            ],
        ),
    ]
