# Generated by Django 4.1.7 on 2023-02-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('lanzamiento', models.DateField()),
                ('premios', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pintura', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('estilo', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('lanzamiento', models.DateField()),
                ('plataforma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videojuego', models.CharField(max_length=50)),
                ('consola', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('coleccion', models.IntegerField()),
            ],
        ),
    ]
